- hosts: all
  vars_files:
    - ../ruby-install/defaults/main.yml
    - ../chruby/defaults/main.yml
  vars:
    ruby_default_version: 2.1.2
    ruby_install_ruby_versions:
      - 1.9.3
      - 2.1.2
    ruby_users:
      - vagrant
      - root
  tasks:
    - include: ../ruby-install/tasks/main.yml
    - include: ../chruby/tasks/main.yml
    - include: tasks/main.yml
